Lab2
gwentenjoyer/csa_labs pull request #2
Opened 2023-09-11 00:03 UTC by gwentenjoyer

lab2 done.

2023-09-20 14:52 UTC, RuslanSlobodian requested changes

2023-09-20 14:52 UTC, RuslanSlobodian commented on lab2/src/main/Main.java
> +        for (int i = 0; i < trains.length; i++) {
2. В основному класі програми (тобто Main) визначити метод, що
створює масив об'єктів класу згідно варіанту та заповнює його тестовими
даними.

2023-09-20 14:52 UTC, RuslanSlobodian commented on lab2/src/main/Main.java
> +            throw new NullPointerException();
Люба операція виконана з посилання, яке рівне null само собою викине NullPointerException, тому нема змісту 
викидати такий ексепшин. Кращий варіант  - llegalArgumentException.
NullPointerException це runtime exception, а відтак unchecked

2023-09-20 14:52 UTC, RuslanSlobodian commented on lab2/src/main/Main.java
> +        for (int i = 0; i < trainsWithDestinationAndGeneralCars.length; i++) {
краще використати цикл типу forech:
for (Train train : trainsWithDestinationAndGeneralCars) {
System.out.println(train);

2023-09-20 14:52 UTC, RuslanSlobodian commented on lab2/src/main/Main.java
> +        ArrayList<Train> arrayList = new ArrayList<>();
Краще використовувати інтерфейс в коді замість класу, який його реалізує:
List<Train> trainsList = new ArrayList<>();

2023-09-20 14:52 UTC, RuslanSlobodian commented on lab2/src/main/Main.java
> +        ArrayList<Train> haveDest = new ArrayList<>();
Краще використовувати інтерфейс в коді замість класу, який його реалізує:
List trainsList = new ArrayList<>();

2023-09-20 14:52 UTC, RuslanSlobodian commented on lab2/src/main/Main.java
> +//        Train[] trainsWithDestination = haveDestination(trains, "Lviv");
Чому закомічено закоментований код?

2023-09-20 19:13 UTC, gwentenjoyer commented on lab2/src/main/Main.java
> +            throw new NullPointerException();
Про IllegalArgumentException в курсі не був, прийму до відома.

2023-09-20 19:50 UTC, gwentenjoyer reviewed
it's should be ok now

2023-09-21 11:43 UTC, RuslanSlobodian approved these changes

2023-09-21 11:43 UTC, merged